export CDH_NIFI_HOME=$PARCELS_ROOT/$PARCEL_DIRNAME/lib/nifi
export CDH_NIFI_TOOLKIT_HOME=$PARCELS_ROOT/$PARCEL_DIRNAME/lib/nifi-toolkit
export CDH_NIFI_XSLT=$PARCELS_ROOT/$PARCEL_DIRNAME/lib/nifi-xslt
export CDH_NIFI_JQ=$PARCELS_ROOT/$PARCEL_DIRNAME/bin/jq
