NIFI_DIRNAME=${PARCEL_DIRNAME:-"NIFI-1.4.0"}
export CDH_NIFI_HOME=$PARCELS_ROOT/$NIFI_DIRNAME/lib/nifi
export CDH_NIFI_TOOLKIT_HOME=$PARCELS_ROOT/$NIFI_DIRNAME/lib/nifi-toolkit
export CDH_NIFI_XSLT=$PARCELS_ROOT/$NIFI_DIRNAME/lib/nifi-xslt

alias jq=$PARCELS_ROOT/$NIFI_DIRNAME/bin/jq
